event_manager/urls.py
from django.urls import path
from . import views

app_name= "event_manager"
  


urlpatterns = [
	path('home/', views.home,name='home'),
	path('category/', views.category1,name='category'),
	path('sponsers/', views.sponsers1,name='sponsers'),
	path('manage_cat/', views.manage_cat,name='manage_cat'),
	path('manage_spon/',views.manage_spon,name='manage_spon'),
	path('catdelete/<int:id>/',views.delcat,name='delcat'),
	path('add_event/', views.add_event,name='add_event'),
	path('deleve/<int:id>/',views.deleve,name='deleve'),
	path('upeve/<int:id>/',views.upeve,name='upeve'),
	path('manage_eve/',views.manage_eve,name='manage_eve'),
	path('updatecat/<int:id>/',views.updatecat,name='upcat'),
	path('delspon/<int:id>/',views.delspon,name='delspon'),
	path('updatespon/<int:id>/',views.updatespon,name='upspon'),
	path('manage_users/',views.manage_users),
	path('manage_b/',views.manage_b),
	path('admin_action/<int:id>/',views.admin_action,name='admin_action'),
	path('confirm/',views.confirm),
	path('cancel/',views.cancel),
	path('viewfeed/',views.viewfeed),
	path('addevent1/', views.addevent1,name='addevent1'),
	path('bookconf/<int:id>/',views.bookconf,name='bconf')


]

event_user/urls.py
from django.urls import path
from . import views

app_name= "event_user"
  


urlpatterns = [
	path('user_event/', views.user_event,name='user_event'),
	path('profile/<int:id>/',views.profile,name='profile'),
	path('view/<int:id>',views.view,name='view'),
	path('book/<int:id>/',views.book,name='book'),
	path('my_book/',views.my_book),
	path('update/',views.updateus),
	path('feedback/',views.feedback1),
	path('cancel/<int:id>/',views.cancel,name='can'),
	path('private/',views.private,name='private'),
	path('book1/',views.book1),
	path('cancel1/<int:id>/',views.cancel1,name='can1'),
	path('rec/',views.rec),


]

eventplanner/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views  


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('signup/', views.signup,name='signup'),
    path('login/', views.login_call,name='login_call'),
    path('logout/', views.logout_call,name='logout_call'),
    path('event_manager/', include('event_manager.urls')),
    path('home/',views.home,name="home"),
    path('event_user/', include('event_user.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    

]
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event_manager/models.py
# Create your models here.
from django.db import models
from eventplanner.models import UserProfile

# Create your models here.
class category(models.Model):
	catname = models.CharField(max_length=50,unique=True)
	desc = models.CharField(max_length=200,null=True)
	dated = models.DateTimeField(auto_now=True,null=True)

class sponsers(models.Model):
	sponser = models.CharField(max_length=50,unique=True)
	logo = models.ImageField(upload_to="product_image", blank=True)


class Event(models.Model):
	name = models.CharField(max_length=100,null=True)
	desc = models.CharField(max_length=200,null=True)
	eve_img = models.ImageField(upload_to="product_image", blank=True,null=True)
	category = models.ForeignKey(category, on_delete=models.CASCADE,null=True)
	sponsers= models.ForeignKey(sponsers,on_delete=models.CASCADE,null=True)
	location= models.CharField(max_length=50,null=True)
	startdate= models.DateField(null=True)
	enddate= models.DateField(null=True)
	speaker_name=models.CharField(max_length=100,null=True)
	added_by = models.ForeignKey(UserProfile,on_delete=models.CASCADE,null=True)

	
class manage_book(models.Model):
	admin_remark=models.CharField(max_length=50,null=True)
	choice=( 
		('confirm', 'confirm'),
        ('cancel', 'cancel'),
        )
	action = models.CharField(choices=choice, max_length=10,null=True)

class venue(models.Model):
	ven=models.CharField(max_length=50)

class decoration_theme(models.Model):
	dec=models.CharField(max_length=50)

class events(models.Model):
	name = models.CharField(max_length=100)
	eve_img = models.ImageField(upload_to="product_image")
	price= models.DecimalField(decimal_places=2, max_digits=12)
	added_by = models.ForeignKey(UserProfile,on_delete=models.CASCADE,null=True)

    
	
# Create your models here.

event_user/models.py
from django.db import models
from eventplanner.models import UserProfile
from event_manager.models import Event,events,venue,decoration_theme

class Booked(models.Model):
	book_id =  models.IntegerField()
	num_of_mem = models.IntegerField()
	user_remark = models.CharField(max_length=100)
	date = models.DateTimeField(auto_now=True)
	e_name = models.ForeignKey(Event, on_delete=models.CASCADE,null=True)
	users = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
	status=models.IntegerField(default=0)


class booking(models.Model):
	book_id =  models.IntegerField()
	num_of_person = models.IntegerField()
	date = models.DateTimeField(auto_now=True)
	ename = models.ForeignKey(events, on_delete=models.CASCADE) 
	venue=models.ForeignKey(venue, on_delete=models.CASCADE)
	decoration_theme=models.ForeignKey(decoration_theme, on_delete=models.CASCADE)
	catering = (
        ('Yes', 'Yes'),
        ('No', 'No'),
        )
	catering = models.CharField(choices=catering, max_length=10)
	status=models.IntegerField(default=0)
	prices= models.IntegerField()
	users = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


class feedback(models.Model):
	message = models.CharField(max_length=100)
	user =  models.ForeignKey(UserProfile, on_delete=models.CASCADE,null=True)
	date = models.DateTimeField(auto_now=True,null=True)

# Create your models here.

event_manager/views.py
from django.shortcuts import render,redirect
from .models import category,Event,sponsers,manage_book,events
from eventplanner.models import UserProfile
import datetime
from django.contrib import messages
from event_user.models import Booked,feedback,booking
from django.conf import settings
from django.core.mail import send_mail




# Create your views here.
def home(request):
	return render(request, "event_manager.html")

def category1(request):
	if request.method=="POST":
		cat = request.POST['name']
		desc = request.POST['desc']
		cobj = category(catname=cat,desc= desc)
		cobj.save()
		messages.success(request, "category added Successfully!")
		return redirect('/event_manager/category/')
	return render(request, "addcategory.html")

def sponsers1(request):
	if request.method=="POST":
		sponser = request.POST['sponser']
		logo = request.FILES['img']
		s= sponsers(sponser=sponser,logo=logo)
		s.save()
		return redirect('/event_manager/sponsers')
	return render(request, "addsponsers.html")



def add_event(request):
	cobjs= category.objects.all()
	spons= sponsers.objects.all()


	if request.method=="POST":
		nm = request.POST['name']
		desc = request.POST['desc']
		img = request.FILES['img']
		start_date= request.POST['sdate']
		end_date= request.POST['edate']
		location= request.POST['location']
		speaker = request.POST['sp']
		catid = request.POST['cat']
		sid= request.POST['s']
		cobj = category.objects.get(id=catid)
		spon = sponsers.objects.get(id=sid)
		
		uobj= UserProfile.objects.get(user__username=request.user)

		pObj= Event(name=nm ,desc=desc, eve_img=img, category=cobj, added_by=uobj,sponsers=spon,startdate=start_date,enddate=end_date,location=location,speaker_name=speaker)
		pObj.save()
		messages.success(request, "Event added Successfully!")
		return redirect('/event_manager/add_event/')

	return render(request, "addevent.html",{'cats':cobjs,'s':spons})

def manage_eve(request):
	eve=Event.objects.all()
	return render(request,"manageeve.html",{'eve':eve})

def deleve(request,id):
	deleve=Event.objects.get(id=id)
	deleve.delete()
	return redirect('/event_manager/manage_eve/')

def upeve(request,id):
	cobjs= category.objects.all()
	upeve=Event.objects.get(id=id)
	spons= sponsers.objects.all()
	if request.method=='POST':
		nm=request.POST['name']
		desc=request.POST['desc']
		location= request.POST['location']
		start_date=request.POST['sdate']
		end_date=request.POST['edate']
		catid = request.POST['cat']
		sid=request.POST['s']
		spon = sponsers.objects.get(id=sid)
		cobj = category.objects.get(id=catid)
		uobj= UserProfile.objects.get(user__username=request.user)
		up=Event.objects.filter(id=id)
		up.update(name=nm ,desc=desc,startdate=start_date,enddate=end_date, category=cobj,sponsers=spon,location=location, added_by=uobj)
		return redirect('/event_manager/manage_eve/')
	return render(request,'updateeve.html',{'eve':upeve,'cats':cobjs,'s':spons})


def manage_cat(request):
	cat=category.objects.all()

	return render(request, "managecat.html",{'cat':cat})

def manage_spon(request):
	spon=sponsers.objects.all()
	return render(request,"managespon.html",{'spon':spon})

   

def delcat(request,id):
	delcate=category.objects.get(id=id)
	delcate.delete()
	return redirect('/event_manager/manage_cat/')

def delspon(request,id):
	delspon=sponsers.objects.get(id=id)
	delspon.delete()
	return redirect('/event_manager/manage_spon/')


def updatecat(request,id):
	upcat=category.objects.get(id=id)
	if request.method=='POST':
		name=request.POST['name']
		desc=request.POST['desc']
		up=category.objects.filter(id=id)
		up.update(catname=name,desc=desc)
		return redirect('/event_manager/manage_cat/')
	return render(request,'catupdate.html',{'cat':upcat})

def updatespon(request,id):
	upspon=sponsers.objects.get(id=id)
	if request.method=='POST':
		name=request.POST['name']
		logo=request.POST['img']
		spon=sponsers.objects.filter(id=id)
		spon.update(sponser=name,logo=logo)
		return redirect('/event_manager/manage_spon/')
	return render(request,'sponupdate.html',{'spon':upspon})

def manage_users(request):
	
	user=UserProfile.objects.filter(usertype='event_user')
	
	return render(request,'manageuser.html',{"user":user})

def manage_b(request):
	bk=booking.objects.all()
	book=Booked.objects.all()
	return render(request,'allbook.html',{'book':book,'bk':bk})

def bookconf(request,id):
	book=booking.objects.filter(id=id)
	book.update(status=1)
	if request.method=='POST':
		remark=request.POST['remark']
		action= request.POST['action']
		if action=='confirm':
			b=booking.objects.get(id=id)
			email=b.users.user.email
			subject = 'Thank you'
			message = 'Your event is confirmed'
			email_from = settings.EMAIL_HOST_USER
			recipient_list = [email,]
			send_mail( subject, message, email_from, recipient_list )
		b=manage_book(admin_remark=remark,action=action)
		b.save()
		return redirect('/event_manager/manage_b/')
	return render(request,'admin_action.html')
	

def admin_action(request,id):
    book=Booked.objects.filter(id=id)
    if request.method=='POST':
    	remark=request.POST['remark']
    	action= request.POST['action']
    	if action=='confirm':
    		book.update(status=1)
    		b=Booked.objects.get(id=id)
    		email=b.users.user.email
    		subject = 'Thank you'
    		message = 'Your event is confirmed'
    		email_from = settings.EMAIL_HOST_USER
    		recipient_list = [email,]
    		send_mail( subject, message, email_from, recipient_list )
    	b=manage_book(admin_remark=remark,action=action)
    	b.save()
    	return redirect('/event_manager/manage_b/')
    return render(request,'admin_action.html')


def confirm(request):
	book=Booked.objects.filter(status=1)
	b = booking.objects.filter(status=1)
	return render(request,'confirm.html',{'book':book,'b':b})
	
def cancel(request): 
	book=Booked.objects.filter(status=0)
	b = booking.objects.filter(status=0)
	return render(request,'cancel.html',{'book':book,'b':b})
	
def viewfeed(request):
	f=feedback.objects.all()
	return render(request,'feed.html',{'f':f})

def addevent1(request):
	if request.method=='POST':
		nm=request.POST['name']
		img = request.FILES['img']
		price= request.POST['price']
		uobj= UserProfile.objects.get(user__username=request.user)

		pObj= events(name=nm , eve_img=img,price=price,added_by=uobj)
		pObj.save()
		messages.success(request, "Event added Successfully!")
		return redirect('/event_manager/addevent1/')
	return render(request, "addevent1.html")

event_user/views.py
from django.shortcuts import render,redirect
from eventplanner.models import UserProfile
from event_manager.models import category,sponsers,Event,events,venue,decoration_theme
from .models import Booked,feedback,booking
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
import random
from django.contrib import messages

from django.contrib.auth import authenticate,login

# Create your views here.


def user_event(request):
	eve=Event.objects.all()
	return render(request,"event_user.html",{'eve':eve,})

def profile(request,id):
	uppro=UserProfile.objects.get(id=id)
	if request.method=='POST':
		fn = request.POST['fname']
		ln = request.POST['lname']
		un = request.POST['uname']
		pwd = request.POST['pwd']
		em = request.POST['email']
		mob = request.POST['mob']
		addr = request.POST['address']
		up=UserProfile.objects.filter(id=id)
		up.update(mobile=mob, address=addr)
		use=User.objects.filter(id=uppro.id)
		use.update(first_name=fn, last_name=ln, username=un, password=make_password(pwd), email=em)
		return redirect('/event_user/profile/')
	return render(request,'event_user.html',{'p':uppro})

def view(request,id):
	eve=Event.objects.get(id=id)
	return render(request,"viewdet.html",{'i':eve})


def book(request,id):
	eve=Event.objects.all()
	if request.method=='POST':
		no_of_mem=request.POST['mem']
		user_re=request.POST['re']
		r=random.randint(10000,99999)
		ev=Event.objects.get(id=id)
		user=UserProfile.objects.get(user__username=request.user)	
		b=Booked(book_id=r,num_of_mem=no_of_mem,user_remark=user_re,users=user,e_name=ev)
		b.save()
		messages.success(request, "booking is sent for approval!")
		return redirect('/event_user/user_event/#team')
	return render(request,'book.html')

def my_book(request):
	book=booking.objects.filter(users__user__username=request.user)
	b=Booked.objects.filter(users__user__username=request.user)
	return render(request,"mybook.html",{'b':b,'book':book})


def updateus(request):
	user=UserProfile.objects.get(user__username=request.user)
	if request.method=='POST':
		fn = request.POST['fname']
		ln = request.POST['lname']
		un = request.POST['uname']
		pwd = request.POST['pwd']
		em = request.POST['email']
		mob = request.POST['mob']
		addr = request.POST['address']
		up=UserProfile.objects.filter(id=user.id)
		up.update(mobile=mob, address=addr)
		use=User.objects.filter(id=user.user.id)
		use.update(first_name=fn, last_name=ln, username=un, password=make_password(pwd), email=em)
		
		user = authenticate(username=un, password=pwd)
		login(request, user)
		return redirect('/event_user/user_event/')
	return render(request,'updateus.html',{'user':user})

def feedback1(request):
	user=UserProfile.objects.get(user__username=request.user)

	message = request.POST['mes']
 
	m=feedback(message=message,user=user)
	m.save()
	return redirect('/event_user/user_event/')


def cancel(request,id):
	b=Booked.objects.get(id=id)
	b.delete()
	return redirect('/event_user/my_book/')
def cancel1(request,id):
	b=booking.objects.get(id=id)
	b.delete()
	return redirect('/event_user/my_book/')


def private(request):
	eve1= events.objects.all()
	ven= venue.objects.all()
	dec= decoration_theme.objects.all()

	if request.method=="POST":
		r=random.randint(10000,99999)
		date = request.POST['date']
		per = request.POST['per']
		
		cat=request.POST['cat']
		eid=request.POST['ev']
		vid = request.POST['v']
		did= request.POST['d']
		eobj = events.objects.get(id=eid)
		vobj = venue.objects.get(id=vid)
		dobj = decoration_theme.objects.get(id=did) 
		
		uobj= UserProfile.objects.get(user__username=request.user)

		pObj= booking(book_id=r ,date=date,num_of_person=per,prices=eobj.price,ename=eobj,venue=vobj,decoration_theme=dobj,catering=cat,users=uobj)
		pObj.save()
		
		messages.success(request, "booking is sent for approval!")
		return render(request,'book1.html',{'price':eobj.price,'event':eobj.name,'pn':per,'date':date,'eid':r}) 
	return render(request, "private.html",{'ev':eve1,'ve':ven,'de':dec})


def book1(request):
	x=1
	eid=request.POST['eid']
	price=request.POST['price']
	date=request.POST['date']
	pn=request.POST['pn']
	event=request.POST['ename']
	print(eid)

	return render(request,'rec.html',{'price1':price,'event1':event,'pn1':pn,'date1':date,'eid1':eid})
	
def rec(request):
	return render(request,"rec.html")

templates/managecat.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
       
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">Event_Planner- Admin Panel</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    
                        
                        <li><a class="dropdown-item" href="/logout/">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            
                            
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Category
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="/event_manager/category/">Add</a>
                                    <a class="nav-link" href="/event_manager/manage_cat/">Manage</a>
                                </nav>
                            </div>
                             <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Sponsers
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="/event_manager/sponsers/">Add</a>
                                    <a class="nav-link" href="/event_manager/manage_spon/">Manage</a>
                                </nav>
                            </div>
                           
                            
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Events
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link" href="/event_manager/add_event/">Add</a>
                                    <a class="nav-link" href="/event_manager/manage_eve/">Manage</a>
                                    
                                </nav>
                            </div>
                                  <a class="nav-link" href="/event_manager/manage_users/">Manage_Users</a>

                             <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Manage Bookings
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link" href="/event_manager/manage_b/">All bookings</a>
                                    <a class="nav-link" href="/event_manager/confirm/">confirm bookings</a>
                                    <a class="nav-link" href="/event_manager/cancel/">cancel bookings</a>
                                </nav>
                            </div>
                                  <a class="nav-link" href="/event_manager/feedback/">view Feedback</a>
   
                                
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small"></div>
                        
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                            
                           
            

            <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Manage Category
                            </div>
                            <div class="card-body">
                                <table id="datatablesSimple">
                                    <thead>
                                        <tr>
                                            <th>No.</th>
                                            <th>Category</th>
                                            <th>Description</th>
                                            <th>Date</th>
                                            <th>Actions</th>
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {%for i in cat%}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{i.catname}}</td>
                                            <td>{{i.desc}}</td>
                                            <td>{{i.dated}}</td>
                                            <td><a href="{%url 'event_manager:delcat' id=i.id %}"><img class="mx-auto rounded-circle" src="{%static 'media/d.png' %}"style="width:50px"></a>
                                            <a href="{%url 'event_manager:upcat' id=i.id%}"><img class="mx-auto rounded-circle" src="{%static 'media/u.png' %}"style="width:50px"></a></td>
                                        </tr>
                                        {%endfor%}

                                    </tbody>                                   

                                </table>
                            </div>
                        </div>
                    


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
</body>
</html>

templates/mybook.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title></title>
  <style type=text/css>
  table, th, td {
  border: 1px solid black;
}
th, td {
  padding: 15px;
}
th {
  text-align: left;
}
table {
  border-spacing: 5px;
}
#t01 {
  width: 100%;
  background-color: #f1f1c1;
}
</style>
<body>
  <h2>My Booking<h2>

<table style="width:100%" id="t01">
  <tr>
    <th>Booking Id</th>
    <th>Event Name</th>
    <th>Booking date</th>
    <th>Booking Status</th>
    <th>Action</th>
  </tr>
    {% for i in b%}
    
  <tr>
  
   <td>{{i.book_id}}</td>
   <td>{{i.e_name.name}}</td>
   <td>{{i.date}}</td>
   <td>{%ifequal i.status 0%}
    <p>pending</p>
    {%else%}
    <p>confirm</p>
    {%endifequal%}
   <td>
{%ifequal i.status 0%}
    <a href="{%url 'event_user:can' id=i.id%}">Cancel</a>
    {%else%}
    <p>confirm</p>
    {%endifequal%}
    </td>
   
  
   {%endfor%}
  </tr>
  
  <tr>
    {%for i in book%}
    <td>{{i.book_id}}</td>
    <td>{{i.ename.name}}</td>
    <td>{{i.date}}</td>
    <td>{%ifequal i.status 0%}
    <p>pending</p>
    {%else%}
    <p>confirm</p>
    {%endifequal%}
   <td>
{%ifequal i.status 0%}
<a href="{%url 'event_user:can1' id=i.id%}">Cancel</a>
    {%else%}
    <p>confirm</p>
    {%endifequal%}
  </tr>
  {%endfor%}
</body>
</table>
</head>
</html>